[tool.mypy]
explicit_package_bases = true

[tool.flake8]
max-line-length = 120
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    "migrations",
    "src_old"
]
ignore = ["W503"]
enable-extensions = ["ANN"]
count = true
statistics = true
show-source = true
docstring-convention = "google"
